// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/google/wire"
)

import (
	_ "github.com/lib/pq"
)

// Injectors from wire.go:

func InitializeMainProcess() (*MainProcess, error) {
	injectableConfig := NewConfigFromEnvironment()
	injectableDatabase, err := NewPQDatabase(injectableConfig)
	if err != nil {
		return nil, err
	}
	injectableServer, err := NewDefaultServer(injectableConfig, injectableDatabase)
	if err != nil {
		return nil, err
	}
	mainProcess, err := NewMainProcess(injectableServer, injectableDatabase)
	if err != nil {
		return nil, err
	}
	return mainProcess, nil
}

// wire.go:

var DefaultProviderSet = wire.NewSet(NewDefaultServer, NewPQDatabase, NewMainProcess, NewConfigFromEnvironment)
